### ISSUE TITLE
Packaging for openSUSE: Is there a way to disable failing tests?

### ISSUE THREAD

**Issue by kastl-ars** [veeso/termscp#272]
I am packaging termscp for openSUSE. The package builds fine, but some of the tests fail.

This could totally be because the build environment is special. All builds are done offline, with all dependencies vendored before and provided during build.

The tests that are failing are the following:

```
[  532s] 
[  532s] failures:
[  532s] 
[  532s] ---- system::keys::keyringstorage::tests::test_system_keys_keyringstorage stdout ----
[  532s] thread 'system::keys::keyringstorage::tests::test_system_keys_keyringstorage' panicked at src/system/keys/keyringstorage.rs:88:9:
[  532s] assertion failed: storage.is_supported()
[  532s] 
[  532s] ---- system::auto_update::test::auto_update stdout ----
[  532s] Checking target-arch... x86_64-unknown-linux-gnu
[  532s] Checking current version... v0.14.0
[  532s] Checking latest released version... thread 'system::auto_update::test::auto_update' panicked at src/system/auto_update.rs:159:18:
[  532s] called `Option::unwrap()` on a `None` value
[  532s] 
[  532s] ---- system::auto_update::test::check_for_updates stdout ----
[  532s] Err(Network("api request failed with status: 403 - for: \"https://api.github.com/repos/veeso/termscp/releases/latest\""))
[  532s] thread 'system::auto_update::test::check_for_updates' panicked at src/system/auto_update.rs:171:9:
[  532s] assertion failed: Update::is_new_version_available().is_ok()
[  532s] 
[  532s] 
[  532s] failures:
[  532s]     system::auto_update::test::auto_update
[  532s]     system::auto_update::test::check_for_updates
[  532s]     system::keys::keyringstorage::tests::test_system_keys_keyringstorage
[  532s] 
[  532s] test result: FAILED. 199 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.02s

```

Is it possible to disable only those tests (and not the tests globally)? Not sure if I could use the `--features` flag for this? But I think there is no feature that disables the auto_update tests...

Thanks in advance,
Johannes

**Comment by veeso** [comment]
Implementation: add a new feature `isolated` to make system and external-resource-dependent tests, not run.

**Comment by kastl-ars** [comment]
Thanks for implementing this feature.

I just updated the package to 0.15.0 and switched to isolated-tests.

I get two failing tests:

```
[  542s] failures:
[  542s] 
[  542s] ---- host::tests::test_host_localhost_change_dir stdout ----
[  542s] thread 'host::tests::test_host_localhost_change_dir' panicked at src/host/mod.rs:679:9:
[  542s] assertion failed: `(left == right)`
[  542s] 
[  542s] Diff < left / right > :
[  542s] <216
[  542s] >217
[  542s] 
[  542s] 
[  542s] 
[  542s] ---- host::tests::test_host_localhost_new stdout ----
[  542s] thread 'host::tests::test_host_localhost_new' panicked at src/host/mod.rs:634:9:
[  542s] assertion failed: `(left == right)`
[  542s] 
[  542s] Diff < left / right > :
[  542s] <216
[  542s] >217
[  542s] 
[  542s] 
[  542s] 
[  542s] 
[  542s] failures:
[  542s]     host::tests::test_host_localhost_change_dir
[  542s]     host::tests::test_host_localhost_new
[  542s] 
[  542s] test result: FAILED. 202 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.03s
```

Not sure if this is related to the new version or a test requires network connectivity. Could you have a look?

Kind Regards,
Johannes
