### ISSUE TITLE
Packaging for openSUSE: tests failing in 0.16.1 (host::localhost::tests::test_host_localhost_change_dir and host::localhost::tests::test_host_localhost_new)

### ISSUE THREAD

**Issue by johanneskastl** [veeso/termscp#313]
Dear Christian,

packaging termscp for openSUSE fails during the tests:

```
[  570s] test system::bookmarks_client::tests::test_system_bookmarks_recents_more_than_limit ... ok
[  570s] 
[  570s] failures:
[  570s] 
[  570s] ---- host::localhost::tests::test_host_localhost_change_dir stdout ----
[  570s] thread 'host::localhost::tests::test_host_localhost_change_dir' panicked at src/host/localhost.rs:636:9:
[  570s] assertion failed: `(left == right)`
[  570s] 
[  570s] Diff < left / right > :
[  570s] <216
[  570s] >217
[  570s] 
[  570s] 
[  570s] 
[  570s] ---- host::localhost::tests::test_host_localhost_new stdout ----
[  570s] thread 'host::localhost::tests::test_host_localhost_new' panicked at src/host/localhost.rs:591:9:
[  570s] assertion failed: `(left == right)`
[  570s] 
[  570s] Diff < left / right > :
[  570s] <216
[  570s] >217
[  570s] 
[  570s] 
[  570s] 
[  570s] 
[  570s] failures:
[  570s]     host::localhost::tests::test_host_localhost_change_dir
[  570s]     host::localhost::tests::test_host_localhost_new
[  570s] 
[  570s] test result: FAILED. 212 passed; 2 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.03s
```

Tests are being run with the following command:

```
/usr/bin/cargo auditable test -j4 --offline --no-fail-fast --features isolated-tests
```

Full buildlog is here:
https://build.opensuse.org/package/live_build_log/home:ojkastl_buildservice:Branch_network_utilities/termscp/openSUSE_Factory/x86_64

Could you please have a look?

Kind Regards,
Johannes

**Comment by veeso** [comment]
Please try now

**Comment by johanneskastl** [comment]
Tthat worked, thanks for your help!
